version: '3'
services:
    rasa:
      container_name: "rasa_server_alc_der"
      user: root
      build: 
        context:  .
      volumes:
      - "./:/app"
      - "./models:/app/models"
      ports: 
        - "5008:5005"
      networks:
        - nueva_red
    action_server:
      container_name: "action_server_alc_der"
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
      ports:
        - 5058:5055

      networks:
        - nueva_red

networks:
  nueva_red:
    external:
      name: nueva_red